[package]
name = "binance_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.1"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
url = "2.2"